#!/usr/bin/with-contenv bash

while [ ! -f "/data/remote/$RCLONE_HEALTH_CHECK_FILE" ]
do
  echo "MergerFS mount not yet active, waiting for rclone mount..."
  sleep 2
done

echo -e "\n=================================================="
echo "Mounting mergerfs: $(date +%Y.%m.%d-%T)"
echo "Using: mergerfs -f -o $MERGERFS_OPTIONS /data/local=$MERGERFS_LOCAL_RWMODE:/data/remote=$MERGERFS_RCLONE_RWMODE /data/union"
echo -e "==================================================\n"

exec s6-setuidgid abc /usr/bin/mergerfs -f -o $MERGERFS_OPTIONS "/data/local=$MERGERFS_LOCAL_RWMODE:/data/remote=$MERGERFS_RCLONE_RWMODE" "/data/union"
echo "Mergerfs mounted!"
