#!/usr/bin/with-contenv bash

echo "Unmounting /data/union"
exec s6-setuidgid root fusermount -uz "/data/union" &
echo "/data/remote has been unmounted"
exec s6-setuidgid root fusermount -uz "/data/remote" &

while [ -f "/data/remote/$RCLONE_HEALTH_CHECK_FILE" ]
do
  echo "/data/remote not disconnected yet, unmounting again..."
  exec s6-setuidgid root fusermount -uz "/data/remote" &
  sleep 2
done
echo "/data/remote has been unmounted!"
