#!/usr/bin/with-contenv bash

while [ ! -f $FILE_TO_WAIT ]
do
  echo "Rclone mount not yet active"
  sleep 2
done

echo "Rclone mount active"

exec s6-setuidgid abc /usr/bin/mergerfs -f -o defaults,category.create=epff,minfreespace=0,allow_other,dropcacheonclose=true,security_capability=false,xattr=nosys,statfs_ignore=ro,use_ino,hard_remove,auto_cache,sync_read,umask=0002,noatime /mnt/local=RW:/mnt/rclone=RW /mnt/unionfs

